---
title: "EDA"
author: "Likhitha, Paulina, Shrihan"
date: "2023-10-10"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
---


```{r, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
library(ezids)
library(ggplot2)
#install.packages(tigris)
library(tigris)
#install.packages("sf")
library(sf)

```



**Load the data file**

```{r Load the data file }

SVI_Data <- read.csv('C:/Users/lkg31/OneDrive/Desktop/DATS-6101-PROJECT/SVI_2020_US.csv')

```

**Remove irrelevant columns**

```{r select columns}

#selecting the required columns by subset function
Clean_data <- subset(SVI_Data, select = c(ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,AREA_SQMI,EPL_POV150,	EPL_UNEMP,	EPL_HBURD,	EPL_NOHSDP,	EPL_UNINSUR,	SPL_THEME1,	RPL_THEME1,	EPL_AGE65,	EPL_AGE17,	EPL_DISABL,	EPL_SNGPNT,	EPL_LIMENG,	SPL_THEME2,	RPL_THEME2,	EPL_MINRTY,	SPL_THEME3,	RPL_THEME3,	EPL_MUNIT,	EPL_MOBILE,	EPL_CROWD,	EPL_NOVEH,	EPL_GROUPQ,	SPL_THEME4,	RPL_THEME4,	SPL_THEMES,	RPL_THEMES
) )

summary(Clean_data)

xkablesummary(Clean_data, title="Clean summary of the data.")

```

```{r show Outliers}
#Display the Outliers in the cleaned data

Ouliers = outlierKD2(Clean_data, RPL_THEME1, rm = FALSE, qqplt = TRUE)
Ouliers = outlierKD2(Clean_data, RPL_THEME2, rm = FALSE, qqplt = TRUE)
Ouliers = outlierKD2(Clean_data, RPL_THEME3, rm = FALSE, qqplt = TRUE)
Ouliers = outlierKD2(Clean_data, RPL_THEME4, rm = FALSE, qqplt = TRUE)
Ouliers = outlierKD2(Clean_data, RPL_THEMES, rm = FALSE, qqplt = TRUE)

```

## Making Maps {.tabset}
```{r}
#import shapefile of all census tracts
#tracts <- st_read("/Users/paulinemnev/Desktop/IntroDataScience/DATS-6101-PROJECT/census_tracts_2020/cb_2020_us_bg_500k.shp")
```


```{r}
#examine on map
a = ggplot() +
  geom_sf(data = tracts, fill = "blue") +
  labs(title = "My Custom Map") +
  theme_minimal()
a
```

