---
title: "EDA"
author: "Likhitha, Paulina, Shrihan"
date: "2023-10-10"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
---


```{r, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# Restart R session

# Load necessary packages
library(ezids)
library(tigris)
library(sf)
library(here)
library(dplyr)
library(leaflet)
library(reshape2)
library(tmap)
library(viridis)
library(stargazer)
library(maps)
library(ggplot2)

```

**First Look at Dataset**

```{r}

SVI_Data <- read.csv("SVI_2020_US.csv")
us_cases <- read.csv('USAFacts/confirmed-covid-19-cases-in-us-by-state-and-county.csv')
us_deaths <- read.csv('USAFacts/confirmed-covid-19-deaths-in-us-by-state-and-county.csv')

head(SVI_Data)
head(us_cases)
head(us_deaths)

```

**Column Subsetting and Renaming**


```{r}

SVI <- subset(SVI_Data, select = c(STATE,STCNTY,COUNTY,FIPS,EP_POV150,EP_LIMENG,EP_AGE65, EP_MINRTY,	EP_UNEMP,	EP_NOHSDP,EP_AGE17,EP_DISABL,EP_SNGPNT,EP_MUNIT,EP_MOBILE,EP_CROWD,EP_NOVEH,EP_GROUPQ,RPL_THEMES) )

# Renaming columns
colnames(SVI)[colnames(SVI) == 'STCNTY'] <- 'county_fips'
us_cases <- rename(us_cases, confirmed_cases = confirmed)



```



**Missing values removal**
```{r}
# Filter out rows with any value equal to -999
SVI <- SVI[rowSums(SVI == -999, na.rm = TRUE) == 0, ]

# Drop rows with missing values
SVI <- na.omit(SVI)

us_cases[is.na(us_cases$confirmed_cases), ]


head(SVI)


```

**Row Subsetting**
```{r}
CA_SVI <- subset(SVI, STATE == "California")
head(CA_SVI)

```

**Formatting**

```{r}
library(dplyr)

format_str <- '%Y-%m-%d'

# Convert the 'date' column to datetime and create a new 'datetime' column
us_cases$datetime <- as.POSIXct(us_cases$date, format = format_str)

# Drop rows that do not refer to a specific county ('Statewide Unallocated')
us_cases <- us_cases[us_cases$county_name != 'Statewide Unallocated', ]

us_cases_ca <- subset(us_cases, state_name == "CA")

# Display the first few rows of the resulting data frame
head(us_cases_ca)

```


```{r}
# Install and load necessary packages
us_cases_grouping_fips <- us_cases_ca %>%
  group_by(county_fips, state_name) %>%
  summarise(max_confirmed_cases = sum(confirmed_cases)) %>%
  arrange(desc(max_confirmed_cases))

us_cases_grouping_county <- us_cases_ca %>%
  group_by(county_name, state_name) %>%
  summarise(max_confirmed_cases = sum(confirmed_cases)) %>%
  arrange(desc(max_confirmed_cases))

result <- bind_cols(us_cases_grouping_fips, us_cases_grouping_county)
Summarized_cases<-result[, 1:4]
new_col_names <- c("fips", "state", "confirmed", "county")
names(Summarized_cases) <- new_col_names

```

```{r}

# Install and load the usmap package
library(usmap)
library(plotly)


# Plot the choropleth map
plot_usmap(
  data = Summarized_cases,
  values = "confirmed",
  include = c("CA"),
  labels = TRUE
) + 
scale_fill_gradient(
  low = "white", high = "red", name = "Confirmed Cases", label = scales::comma) + 
labs(title = "COVID-19 Confirmed Cases in California Counties") +
theme(legend.position = "right")

```

```{r}
us_cases_all_counties <- us_cases_ca %>%
  group_by(county_fips, county_name, state_name) %>%
  summarise(confirmed_cases = sum(confirmed_cases)) %>%
  arrange(desc(confirmed_cases))

# Display the result
head(us_cases_all_counties)

# Group by Fips, County, and State, and calculate the mean of selected indicators
svi_all_counties <- SVI %>%
  group_by(county_fips, COUNTY, STATE) %>%
  summarise(
    EP_POV150 = mean(EP_POV150),
    EP_LIMENG = mean(EP_LIMENG),
    EP_AGE65 = mean(EP_AGE65),
    EP_MINRTY = mean(EP_MINRTY),
    EP_UNEMP = mean(EP_UNEMP),
    EP_NOHSDP = mean(EP_NOHSDP),
    EP_AGE17 = mean(EP_AGE17),
    EP_DISABL = mean(EP_DISABL),
    EP_SNGPNT = mean(EP_SNGPNT),
    EP_MUNIT = mean(EP_MUNIT),
    EP_MOBILE = mean(EP_MOBILE),
    EP_CROWD = mean(EP_CROWD),
    EP_NOVEH = mean(EP_NOVEH),
    EP_GROUPQ = mean(EP_GROUPQ),
    RPL_THEMES = mean(RPL_THEMES)
  )
svi_all_counties_ca <- subset(svi_all_counties, STATE == "California")
# Merge with us_cases_all_counties and sort by confirmed_cases
svi_all_counties_cases <- merge(svi_all_counties_ca, us_cases_all_counties, by = 'county_fips') %>%
  arrange(desc(confirmed_cases))

# Remove unnecessary columns
svi_all_counties_cases <- select(svi_all_counties_cases, -county_name, -state_name)

# Display the result
head(svi_all_counties_cases)

```

**Create timeline of covid**
```{r}




```


**Create correlation matrix**
```{r}




```

**Create MLR for confirmed cases**
```{r}




```






<<<<<<< HEAD
=======




```{r}
nrow(us_cases)
nrow(svi)
#merging
covid_svi <- merge(svi, us_cases, by.svi = "state_fips")

nrow(covid_svi)


```
>>>>>>> 5397221cb8486660c48784029f794a7b309ba6a1
